export const DAY_IN_MILLIS = 1000 * 60 * 60 * 24;

export const API_URL = import.meta.env.VITE_API_SERVER_URL;

export const DNS_QUERY_TYPES: Record<string, { label: string; description: string }> = {
    1: { label: "A", description: "IPv4 Address record" },
    2: { label: "NS", description: "Nameserver record" },
    3: { label: "MD", description: "Mail Destination record (Obsolete)" },
    4: { label: "MF", description: "Mail Forwarder record (Obsolete)" },
    5: { label: "CNAME", description: "Canonical Name record" },
    6: { label: "SOA", description: "Start of Authority record" },
    7: { label: "MB", description: "Mailbox Domain Name record (Experimental)" },
    8: { label: "MG", description: "Mail Group Member record (Experimental)" },
    9: { label: "MR", description: "Mail Rename Domain Name record (Experimental)" },
    10: { label: "NULL", description: "Null Resource record (Experimental)" },
    11: { label: "WKS", description: "Well Known Service record (Deprecated)" },
    12: { label: "PTR", description: "Pointer record for reverse DNS lookups" },
    13: { label: "HINFO", description: "Host Information record" },
    14: { label: "MINFO", description: "Mailbox Information record" },
    15: { label: "MX", description: "Mail Exchange record" },
    16: { label: "TXT", description: "Text record for arbitrary data" },
    17: { label: "RP", description: "Responsible Person record" },
    18: { label: "AFSDB", description: "AFS Database record" },
    19: { label: "X25", description: "X.25 PSDN Address record" },
    20: { label: "ISDN", description: "ISDN Address record" },
    21: { label: "RT", description: "Route Through record" },
    22: { label: "NSAP", description: "NSAP Address record" },
    23: { label: "NSAP-PTR", description: "NSAP Pointer record" },
    24: { label: "SIG", description: "Security Signature record" },
    25: { label: "KEY", description: "Security Key record" },
    26: { label: "PX", description: "X.400 Mail Mapping record" },
    27: { label: "GPOS", description: "Geographical Position record (Withdrawn)" },
    28: { label: "AAAA", description: "IPv6 Address record" },
    29: { label: "LOC", description: "Location Information record" },
    30: { label: "NXT", description: "Next Domain record (Obsolete)" },
    31: { label: "EID", description: "Endpoint Identifier record" },
    32: { label: "NIMLOC", description: "Nimrod Locator record" },
    33: { label: "SRV", description: "Service Location record" },
    34: { label: "ATMA", description: "ATM Address record" },
    35: { label: "NAPTR", description: "Naming Authority Pointer record" },
    36: { label: "KX", description: "Key Exchanger record" },
    37: { label: "CERT", description: "Certificate record" },
    38: { label: "A6", description: "IPv6 Address record (Obsolete)" },
    39: { label: "DNAME", description: "Delegation Name record" },
    40: { label: "SINK", description: "Kitchen Sink record (Experimental)" },
    41: { label: "OPT", description: "EDNS0 Option record" },
    42: { label: "APL", description: "Address Prefix List record" },
    43: { label: "DS", description: "Delegation Signer record for DNSSEC" },
    44: { label: "SSHFP", description: "SSH Public Key Fingerprint record" },
    45: { label: "IPSECKEY", description: "IPSEC Key record" },
    46: { label: "RRSIG", description: "DNSSEC Signature record" },
    47: { label: "NSEC", description: "Next Secure record for DNSSEC" },
    48: { label: "DNSKEY", description: "DNS Key record for DNSSEC" },
    49: { label: "DHCID", description: "DHCP Information record" },
    50: { label: "NSEC3", description: "Next Secure record Version 3 for DNSSEC" },
    51: { label: "NSEC3PARAM", description: "NSEC3 Parameters record" },
    52: { label: "TLSA", description: "TLSA Certificate Association record" },
    53: { label: "SMIMEA", description: "S/MIME Certificate Association record" },
    55: { label: "HIP", description: "Host Identity Protocol record" },
    56: { label: "NINFO", description: "NINFO record" },
    57: { label: "RKEY", description: "RKEY record" },
    58: { label: "TALINK", description: "Trust Anchor LINK record" },
    59: { label: "CDS", description: "Child DS record" },
    60: { label: "CDNSKEY", description: "Child DNSKEY record" },
    61: { label: "OPENPGPKEY", description: "OpenPGP Public Key record" },
    62: { label: "CSYNC", description: "Child-To-Parent Synchronization record" },
    63: { label: "ZONEMD", description: "Zone Message Digest record" },
    64: { label: "SVCB", description: "Service Binding record" },
    65: { label: "HTTPS", description: "HTTPS Binding record" },
    99: { label: "SPF", description: "Sender Policy Framework record" },
    100: { label: "UINFO", description: "IANA-Reserved UINFO record" },
    101: { label: "UID", description: "IANA-Reserved UID record" },
    102: { label: "GID", description: "IANA-Reserved GID record" },
    103: { label: "UNSPEC", description: "IANA-Reserved UNSPEC record" },
    249: { label: "TKEY", description: "Transaction Key record" },
    250: { label: "TSIG", description: "Transaction Signature record" },
    251: { label: "IXFR", description: "Incremental Zone Transfer record" },
    252: { label: "AXFR", description: "Full Zone Transfer record" },
    253: { label: "MAILB", description: "Transfer Mailbox Records" },
    254: { label: "MAILA", description: "Transfer Mail Agent Records" },
    255: { label: "ANY", description: "Request for all records" },
    256: { label: "URI", description: "URI record" },
    257: { label: "CAA", description: "Certification Authority Authorization record" },
    32768: { label: "TA", description: "DNSSEC Trust Authorities record" },
    32769: { label: "DLV", description: "DNSSEC Lookaside Validation record" },
};

export const RESPONSE_SOURCES: Record<string, { label: string }> = {
    0: { label: "Blocked" },
    1: { label: "Allowed" },
    2: { label: "Cache" },
    3: { label: "Recursion Disabled" },
    4: { label: "Upstream" },
    // Fallback value in case response source is missing for whatever reason
    unknown: { label: "Unknown" },
};
