[package]
name = "o-dns-lib"
version = "0.1.0"
edition = "2021"

[features]
"default" = ["edns"]
"edns" = []

[dependencies]
anyhow = "1.0.89"
cfg-if = "1.0.0"
proptest = "1.5.0"
proptest-derive = "0.5.0"
thiserror = "1.0.63"
